config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Defines the root path route ("/")
  root "lessons#index"

  resources :lessons
  resources :notes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lesson.rb
require 'hatch'

class Lesson < ApplicationRecord
  include Hatch

  belongs_to :user

  def self.search(header)
    lessons = header ? Lesson.where("lower(header) LIKE ?", "%#{header.downcase}%") : Lesson.all
  end

  certifies(:header, :not_empty, "This is an error! Where's my header?!")

  certify(:text, 'Logical text should contain more than 20 symbols') do |text|
    text.length > 20
  end
end

app/models/note.rb
class Note < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lessons

  pay_customer stripe_attributes: :stripe_attributes
  # Or using a lambda:
  # pay_customer stripe_attributes: ->(pay_customer) { metadata: { { user_id: pay_customer.owner_id } } }

  def stripe_attributes(pay_customer)
    {
      address: {
        city: pay_customer.owner.city,
        country: pay_customer.owner.country
      },
      metadata: {
        pay_customer_id: pay_customer.id,
        user_id: id # or pay_customer.owner_id
      }
    }
  end

  def pay_should_sync_customer?
    # super will invoke Pay's default (e-mail changed)
    super || self.saved_change_to_address? || self.saved_change_to_name?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_lesson, only: %i[ show edit update destroy ]
  before_action :enable_search, only: :index

  # GET /lessons or /lessons.json
  def index
    @lessons = Lesson.search(params[:search])
  end

  # GET /lessons/1 or /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons or /lessons.json
  def create
    pp lesson_params

    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to lesson_url(@lesson), notice: "Lesson was successfully created." }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to lesson_url(@lesson), notice: "Lesson was successfully updated." }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1 or /lessons/1.json
  def destroy
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to lessons_url, notice: "Lesson was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    def enable_search
      @enable_search = true
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      params.require(:lesson).permit(:header, :text, :data).merge(user_id: current_user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MaxPay</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid" style="margin-left: 10%">
          <%= link_to "MaxPay", root_path, class: "navbar-brand" %>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
<!--            список с кнопками-->
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <%= link_to "Lessons", lessons_path, class: "nav-link active" %>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link_1</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link_2</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link_3</a>
              </li>
            </ul>

            <% if @enable_search %>
              <%= form_tag "#", :method => "get", class: "d-flex", style: "margin-right: 10px" do %>
                <%= text_field_tag :search, params[:search], class: "form-control me-2" %>
                <%= submit_tag("Search", :name => nil, class: 'btn btn-outline-success') %>
              <% end %>
            <% end %>

            <div class="d-flex" role="logout" style="margin-right: 10%">
              <% if current_user %>
                <div class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="bi bi-person"></i>Account
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">My profile</a></li>
                    <li><a class="dropdown-item" href="#">My lessons</a></li>
                    <li><a class="dropdown-item" href="#">My payments</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li>
                      <div class="dropdown-item-text">
                        <%= link_to "Logout", destroy_user_session_path, data: { "turbo-method": :delete, turbo_confirm: 'Are you sure you want to logout?' }, class: "btn btn-danger" %>
                      </div>
                    </li>
                  </ul>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </nav>
    </header>

    <div style="margin-left: 10%">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= form_with(model: @lesson) do |form| %>
  <%# if lesson.errors.any? %>
<!--    <div style="color: red">-->
<!--      <h2><%#= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>-->

<!--      <ul>-->
        <%# lesson.errors.each do |error| %>
<!--          <li><%#= error.full_message %></li>-->
        <%# end %>
<!--      </ul>-->
<!--    </div>-->
  <%# end %>

  <div>
    <%= form.label :header, style: "display: block" %>
    <%= form.text_field :header %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/lessons/_lesson.html.erb
<div id="<%= dom_id lesson %>">
  <p>
    <strong>Header:</strong>
    <%= lesson.header %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= lesson.text %>
  </p>

  <p>
    <strong>User:</strong>
    <%= lesson.user_id %>
  </p>

  <p>
    <strong>Data:</strong>
    <%= lesson.data %>
  </p>

</div>

app/views/lessons/edit.html.erb
<h1>Editing lesson</h1>

<%= render "form", lesson: @lesson %>

<br>

<div>
  <%= link_to "Show this lesson", @lesson %> |
  <%= link_to "Back to lessons", lessons_path %>
</div>

app/views/lessons/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Lessons</h1>

<div id="lessons">
  <% @lessons.each do |lesson| %>
    <%= render lesson %>
    <p>
      <%= link_to "Show this lesson", lesson %>
    </p>
  <% end %>
</div>

<%= link_to "New lesson", new_lesson_path %>

app/views/lessons/new.html.erb
<h1>New lesson</h1>

<%= render "form", lesson: @lesson %>

<br>

<div>
  <%= link_to "Back to lessons", lessons_path %>
</div>

app/views/lessons/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @lesson %>

<div>
  <%= link_to "Edit this lesson", edit_lesson_path(@lesson) %> |
  <%= link_to "Back to lessons", lessons_path %>

  <%= button_to "Destroy this lesson", @lesson, method: :delete %>
</div>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Show this note", @note %> |
  <%= link_to "Back to notes", notes_path %>
</div>

app/views/notes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Notes</h1>

<div id="notes">
  <% @notes.each do |note| %>
    <%= render note %>
    <p>
      <%= link_to "Show this note", note %>
    </p>
  <% end %>
</div>

<%= link_to "New note", new_note_path %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Back to notes", notes_path %>
</div>

app/views/notes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @note %>

<div>
  <%= link_to "Edit this note", edit_note_path(@note) %> |
  <%= link_to "Back to notes", notes_path %>

  <%= button_to "Destroy this note", @note, method: :delete %>
</div>